
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 6;
  public static final int lbracket = 29;
  public static final int instr_out = 26;
  public static final int inst_switch = 15;
  public static final int op_arithmetical = 10;
  public static final int Void = 7;
  public static final int inst_elif = 13;
  public static final int op_relational = 8;
  public static final int string = 5;
  public static final int inst_case = 16;
  public static final int spc_asginc = 40;
  public static final int spc_asgdiv = 39;
  public static final int op_logical = 9;
  public static final int spc_dec = 38;
  public static final int two_points = 33;
  public static final int instr_in = 25;
  public static final int EOF = 0;
  public static final int inst_break = 17;
  public static final int spc_asgmul = 36;
  public static final int rbracket = 30;
  public static final int error = 1;
  public static final int inst_call = 24;
  public static final int lparen = 27;
  public static final int inst_default = 18;
  public static final int dconst = 23;
  public static final int inst_main = 34;
  public static final int inst_while = 19;
  public static final int rparen = 28;
  public static final int id = 3;
  public static final int inst_function = 21;
  public static final int inst_if = 12;
  public static final int inst_for = 20;
  public static final int spc_asgdec = 37;
  public static final int inst_else = 14;
  public static final int character = 2;
  public static final int spc_inc = 41;
  public static final int inst_return = 22;
  public static final int id_main = 35;
  public static final int nextinstr = 31;
  public static final int op_assig = 11;
  public static final int number = 4;
  public static final int separator = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "character",
  "id",
  "number",
  "string",
  "bool",
  "Void",
  "op_relational",
  "op_logical",
  "op_arithmetical",
  "op_assig",
  "inst_if",
  "inst_elif",
  "inst_else",
  "inst_switch",
  "inst_case",
  "inst_break",
  "inst_default",
  "inst_while",
  "inst_for",
  "inst_function",
  "inst_return",
  "dconst",
  "inst_call",
  "instr_in",
  "instr_out",
  "lparen",
  "rparen",
  "lbracket",
  "rbracket",
  "nextinstr",
  "separator",
  "two_points",
  "inst_main",
  "id_main",
  "spc_asgmul",
  "spc_asgdec",
  "spc_dec",
  "spc_asgdiv",
  "spc_asginc",
  "spc_inc"
  };
}

